name: hadoop-cluster

x-worker-common-config:
  &worker-common-config
  image: apache/hadoop:3.4.1
  volumes:
      - ./configuration/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./configuration/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./configuration/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./configuration/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
  depends_on:
    - namenode
    - resourcemanager
  command: >
    bash -c "
      hdfs datanode &
      yarn nodemanager &
      tail -f /dev/null
    "
    
services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
      - "50070:50070"
    volumes:
      - ./configuration/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./configuration/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./configuration/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./configuration/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./scripts/start-hdfs.sh:/start-hdfs.sh
    command: ["/bin/bash", "/start-hdfs.sh"]
    # command: >
    #   bash -c "
    #     hdfs namenode -format -clusterID CID-2947af0f-b46f-497c-8152-2c9ec196a3d4 -force &&
    #     hdfs dfs -chmod 777 /
    #     hdfs namenode
    #   "

  resourcemanager:
    image: apache/hadoop:3.4.1
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - "8088:8088"
      - "8032:8032"
    volumes:
      - ./configuration/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./configuration/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./configuration/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./configuration/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
    command: >
      bash -c "yarn resourcemanager"

  worker-1:
    container_name: worker-1
    hostname: worker-1
    <<: *worker-common-config

  worker-2:
    container_name: worker-2
    hostname: worker-2
    <<: *worker-common-config

  worker-3:
    container_name: worker-3
    hostname: worker-3
    <<: *worker-common-config

  # HIVE ──────────────────────────────────────────

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql
  
  metastore:
    image: apache/hive:4.0.1
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
        - '9083:9083'
    volumes:
        - warehouse:/opt/hive/data/warehouse
        - type: bind
          source: ./drivers/postgresql-42.2.23.jar
          target: /opt/hive/lib/postgres.jar
        - hadoop-conf:/opt/hadoop/etc/hadoop/
        - type: bind
          source: ./configuration/core-site.xml
          target: /opt/hadoop/etc/hadoop/core-site.xml

  hiveserver2:
    image: apache/hive:4.0.1
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - hadoop-conf:/opt/hadoop/etc/hadoop/
      - type: bind
        source: ./configuration/core-site.xml
        target: /opt/hadoop/etc/hadoop/core-site.xml

  hue:
    image: gethue/hue:latest
    container_name: hue
    depends_on:
      - hiveserver2
    volumes:
      - ./hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini:ro
      - ./configuration/hive-site.xml:/opt/hue/desktop/conf/hive-site.xml
    ports:
      - '8888:8888'

volumes:
  hive-db:
  warehouse:
  hadoop-conf: